# Generated by Django 4.2.6 on 2023-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock_keeping_unit_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock keeping unit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
