# Generated by Django 4.2.6 on 2023-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_stock_keeping_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0, help_text='How many of this product are in stock?'),
        ),
    ]
